<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUZy8a2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUZy8a2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUZy8a2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUZy8a2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUZy8a2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'UZy8a2x',
    'container.build_id' => 'aedeaf44',
    'container.build_time' => 1577413616,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUZy8a2x');
