<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8puMzGE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8puMzGE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8puMzGE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8puMzGE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8puMzGE\App_KernelDevDebugContainer([
    'container.build_hash' => '8puMzGE',
    'container.build_id' => 'ba7e505c',
    'container.build_time' => 1577337978,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8puMzGE');
